pipeline {
    agent any
    environment {
      github = credentials('github')
      dockerhub = credentials('dockerhub')
    }
     stages {
        stage('build') {
          when {
           allOf {
            changeset "customers/**"
            not { changeset pattern: "customers/Jenkinsfile" }
          }
}
           steps {
               sh '''
                 until docker container ls ; do sleep 3 ;done && docker build -t ${dockerhub_USR}/customer-info:customers-${GIT_COMMIT} ./customers/
                 docker login -u ${dockerhub_USR} -p ${dockerhub_PSW} && docker push ${dockerhub_USR}/customer-info:customers-${GIT_COMMIT}
                 '''
           }
        }
       stage('deploy') {
        
          when {
           allOf {
            changeset "customers/**"
            not { changeset pattern: "customers/Jenkinsfile" }
          }
}

           steps {
               sh '''
                     git config --global user.email "khanshehbaz104@gmail.com" 
                     git checkout argocd
                     git pull origin argocd
                     export image_tag="${dockerhub_USR}/customer-info:customers-${GIT_COMMIT}" 
                     yq eval '.spec.template.spec.containers[0].image = env(image_tag)' -i ./manifests/customers.yaml
                     git add . 
                     git commit -m "Updated image tag for customers" 
                     git push https://${github_USR}:${github_PSW}@github.com/shehbaz-pathan/argocd-jenkins.git
                  '''
           }
       }

     }
}
