apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: customers
  labels:
    app: customers
spec:
  revisionHistoryLimit: 3
  replicas: 1
  selector:
    matchLabels:
      app: customers
  template:
    metadata:
      labels:
        app: customers
    spec:
      containers:
        - image: 6255/customer-info:customers-f6df5d5aa3d3ebdaf517e872b3fdcc9f2e803d2f
          imagePullPolicy: Always
          name: svc
          ports:
            - containerPort: 3000
  strategy:
    canary:
      steps:
        - setWeight: 10
        - pause:
            duration: 2m
        - setWeight: 20
        - pause:
            duration: 2m
        - setWeight: 50
        - pause:
            duration: 2m
